include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    omit_local_variable_types: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
