// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmXszfTDkvTLqZRrJkqlZtLJugh4AtEHs',
    appId: '1:61255582270:web:98092cd961cce78b8c076f',
    messagingSenderId: '61255582270',
    projectId: 'tercihcepte',
    authDomain: 'tercihcepte.firebaseapp.com',
    storageBucket: 'tercihcepte.firebasestorage.app',
    measurementId: 'G-THZ21NDTZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfoJLyqAqBL7CA56PXEmfFOQqvbYvuXao',
    appId: '1:61255582270:android:1d441ac4e204ea848c076f',
    messagingSenderId: '61255582270',
    projectId: 'tercihcepte',
    storageBucket: 'tercihcepte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFhKn7Hj57MlWpXENNghZ_yjfoLTSOFYY',
    appId: '1:61255582270:ios:aec5c906aacc50118c076f',
    messagingSenderId: '61255582270',
    projectId: 'tercihcepte',
    storageBucket: 'tercihcepte.firebasestorage.app',
    iosBundleId: 'com.tercihcepte.tercihcepte',
  );
}
